# Generated by Django 5.2.13 on 2026-04-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vacancy_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vacancy',
            name='vacancy_active_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='vacancy',
            name='vacancy_active_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='vacancy',
            name='vacancy_active_type_idx',
        ),
    ]
